### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by ysora** [liuqivandy/scRNABatchQC#1]
X = Read10X(myfile, gene.column = 1, unique.features = T )
  S1 = CreateSeuratObject(X)
  result = scRNABatchQC(inputs = list(S1))

When I run this codes, the following time out error occurs.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [www.webgestalt.org] Resolving timed out after 10000 milliseconds

What should I do??

**Comment by shengqh** [comment]
Hi, Ysora:

Would you please install the official WebGestaltR and try again?

    install.packages("WebGestaltR")
